### ISSUE TITLE
Setting up ESLint and Prettier

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/Full-Stack-Development-Learning-Path#126]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AbhijithGanesh** [comment]
Settings up ESLint and Prettier for github workflows? I think I can work on this, can you please assign me?

**Comment by kaiwalyakoparkar** [comment]
Thank you so much for you interest @AbhijithGanesh but this repo mainly consists of issues that I am practicing to work on. Hope you understand :)
