### ISSUE TITLE
Server Discovery And Monitoring engine is deprecated

### ISSUE THREAD

**Issue by Neeteshking21** [kaiwalyakoparkar/Full-Stack-Development-Learning-Path#154]
**Describe the bug**
Server Discovery And Monitoring engine is deprecated since Mongoose 5.7.1  release.
it can become a bug in the future.

**To Reproduce**
1. Go to 'Back-End'/jonsa Node+mongoose.../server.js'
2. Scroll down to 'line number 18, 19'
3. see    " useCreateIndex: true,
              useFindAndModify: false"

**Expected behavior**
You don't need to specify them. It may raise a bug in the future.

**Link that can help you**
[click Here](https://stackoverflow.com/questions/57895175/server-discovery-and-monitoring-engine-is-deprecated)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version latest

**Smartphone (please complete the following information):**

**Comment by kaiwalyakoparkar** [comment]
It seems this issue was solved by a PR so I will close this issue now. Thanks for contributing
