### ISSUE TITLE
Front-end Frameworks in Front-End folder

### ISSUE THREAD

**Issue by ShaileshKumar007** [kaiwalyakoparkar/Full-Stack-Development-Learning-Path#167]
**Is your feature request related to a problem? Please describe.**
I think it's good to have a framework folder inside the Front-End folder.

**Describe the solution you'd like**
We can create a folder named "Front-End-Frameworks" inside the Front-End folder where we can list the items related to this and some resources also

**Describe alternatives you've considered**
We can also make folder name "Frameworks" with front-end and back-end folders. And then we can add different frameworks for front-end, back-end, etc. in this folder.

**Additional context**

**Comment by kaiwalyakoparkar** [comment]
Thank you so much for the suggestion. I will surely look into it once we have more than 1 frameworks.
