### ISSUE TITLE
Add header image to `README.md`

### ISSUE THREAD

**Issue by vikasganiga05** [kaiwalyakoparkar/Full-Stack-Development-Learning-Path#275]
**Is your feature request related to a problem? Please describe.**
No, it's just an improvement to `README.md`. Add header image to the top of the readme file. Which makes the `README.md` file look attractive.

**Describe the solution you'd like**
I used a tool called [GitHub Socialify](https://socialify.git.ci/) to generate the following header images :point_down:.

> ![Full-Stack-Development-Learning-Path](https://socialify.git.ci/kaiwalyakoparkar/Full-Stack-Development-Learning-Path/image?description=1&font=Inter&forks=1&issues=1&language=1&name=1&owner=1&pattern=Solid&pulls=1&stargazers=1&theme=Dark)
> [Customize This :point_up:](https://socialify.git.ci/kaiwalyakoparkar/Full-Stack-Development-Learning-Path/image?description=1&font=Inter&forks=1&issues=1&language=1&name=1&owner=1&pattern=Solid&pulls=1&stargazers=1&theme=Dark)

> ![Full-Stack-Development-Learning-Path](https://socialify.git.ci/kaiwalyakoparkar/Full-Stack-Development-Learning-Path/image?description=1&font=Inter&forks=1&issues=1&language=1&name=1&owner=1&pattern=Plus&pulls=1&stargazers=1&theme=Light)
> [Customize This :point_up: ](https://socialify.git.ci/kaiwalyakoparkar/Full-Stack-Development-Learning-Path/image?description=1&font=Inter&forks=1&issues=1&language=1&name=1&owner=1&pattern=Plus&pulls=1&stargazers=1&theme=Light)

**Describe alternatives you've considered**
if you don't want to use tool generated image. You can create it from scratch :slightly_smiling_face:.

**Additional context**
No additional context.

**Comment by kaiwalyakoparkar** [comment]
Hey @vikasganiga05 would you like to go ahead and create a PR for this issue?

**Comment by vikasganiga05** [comment]
> Hey @vikasganiga05 would you like to go ahead and create a PR for this issue?

Hi, Thanks! I like to work on this issue :+1: . Which header image to add dark or light?
