### ISSUE TITLE
Update the style of INDEX section

### ISSUE THREAD

**Issue by vikasganiga05** [kaiwalyakoparkar/Full-Stack-Development-Learning-Path#294]
**Is your feature request related to a problem? Please describe.**
The current style of the index section is not looking good.

**Describe the solution you'd like**
My suggestion is to replace bullet points with the markdown checkboxes.

**Describe alternatives you've considered**
I not found any other alternatives.

**Additional context**
> Screenshot

![image](https://user-images.githubusercontent.com/74750414/162588844-abf3616b-bcdd-4eb6-96aa-ab97f241862d.png)

**Comment by kaiwalyakoparkar** [comment]
@vikasganiga05 hmm nice idea. But what would be the purpose of checkboxes if this things are already done. They are not any kind of list :thinking:

**Comment by vikasganiga05** [comment]
> @vikasganiga05 hmm nice idea. But what would be the purpose of checkboxes if this things are already done. They are not any kind of list thinking

Yeah! your right. I tried the following format on markdown but it doesn't render it properly :point_down: 
![image](https://user-images.githubusercontent.com/74750414/162621234-a8b2fe13-89ae-4ae5-9c25-f1c403df7bae.png)

You can close this issue :slightly_smiling_face:

**Comment by kaiwalyakoparkar** [comment]
> > @vikasganiga05 hmm nice idea. But what would be the purpose of checkboxes if this things are already done. They are not any kind of list thinking
> 
> Yeah! your right. I tried the following format on markdown but it doesn't render it properly point_down ![image](https://user-images.githubusercontent.com/74750414/162621234-a8b2fe13-89ae-4ae5-9c25-f1c403df7bae.png)
> 
> You can close this issue slightly_smiling_face

Ah, no worries. We will come up with some alternative method which renders properly
