### ISSUE TITLE
Add the index to the Readme file

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/Full-Stack-Development-Learning-Path#42]
Add the index with the links to the every topic learnt during the tenure

**Comment by Deepa-chaurasiya01** [comment]
Hello, Sir, I'd like to work on this, may I?

**Comment by kaiwalyakoparkar** [comment]
> Hello, Sir, I'd like to work on this, may I?

Okay, go ahead

**Comment by Deepa-chaurasiya01** [comment]
Sure sir

**Comment by Deepa-chaurasiya01** [comment]
Sir, could you please unassign me? As I won't be able to continue on this project.
I have insem exams and companies exams.

**Comment by kaiwalyakoparkar** [comment]
@Deepa-chaurasiya01 Sure, thanks for contributing so far :handshake:

**Comment by vikasganiga05** [comment]
Hi Kaiwalya, I like to work on this issue. Please assign me :slightly_smiling_face: 
I already started working on it :point_down: 

#### Screenshot
![image](https://user-images.githubusercontent.com/74750414/159106782-09375c14-d7f2-4ff2-b40b-d63da5f8e5af.png)
