### ISSUE TITLE
add .vscode folder to .gitignore

### ISSUE THREAD

**Issue by yashsehgal** [kaiwalyakoparkar/Full-Stack-Development-Learning-Path#95]
**Describe the bug**
Your `vscode` folder with some editor settings is also being uploaded on GitHub. You can add the `.vscode` folder to the `.gitignore` module.

**Comment by kaiwalyakoparkar** [comment]
Oh! Thanks for pointing that. So if I add it now and then push the changes will it be changed here as well?

**Comment by yashsehgal** [comment]
yup, that folder will be ignored (removed) and not be committed 👍🏽
