### ISSUE TITLE
Change Licence to MIT

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/Full-Stack-Development-Learning-Path#98]
Current License is GNU which needs to be changed to the MIT license

**Comment by ahcodes** [comment]
Hi Kaiwalya, I'd like to do this. Could you assign me, please? Thanks!

**Comment by kaiwalyakoparkar** [comment]
Sure @ahcodes Go for it :) I have assigned it to you now!

**Comment by ahcodes** [comment]
@kaiwalyakoparkar I changed the license. Here's my PR: https://github.com/kaiwalyakoparkar/Full-Stack-Development-Learning-Path/pull/99

I'm a newbie so I might have done some things wrong, let me know if I need to correct something related to this issue, thanks!

**Comment by kaiwalyakoparkar** [comment]
@ahcodes There are some small changes suggested. :)

**Comment by ahcodes** [comment]
> @ahcodes There are some small changes suggested. :)

Changes addressed.
